apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustermonitor-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: clustermonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustermonitor
  template:
    metadata:      
      name: clustermonitor
      namespace: {{ .Release.Namespace }}
      labels:
        app: clustermonitor
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- if .Values.priorityClassDefault.enabled }}
      priorityClassName: spyderbat-high-priority
{{- end }}
      containers:
        - name: clustermonitor
          image: {{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullpolicy }}
          env:
            - name: AGENT_REGISTRATION_CODE
              value: {{ .Values.nanoagent.agentRegistrationCode  }}
            - name: ORC_URL
              value: {{  .Values.nanoagent.orcurl }}
            - name: http_proxy
              value: {{  .Values.nanoagent.httpproxy }}
            - name: https_proxy
              value: {{ .Values.nanoagent.httpsproxy }}
            - name: HTTP_PROXY
              value: {{ .Values.nanoagent.httpproxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.nanoagent.httpsproxy }}
            - name:  SPYDERBAT_TAGS
              value: {{ .Values.spyderbat_tags }}
            - name: K8SMONITOR
              value: "yes"
            - name: CLUSTER_NAME
              value: {{ .Values.CLUSTER_NAME }}
            - name: OMITENVIRONMENT
              value: {{ .Values.OMITENVIRONMENT }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}        
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
