{{- if .Values.priorityClassDefault.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: spyderbat-high-priority
value: {{ .Values.priorityClassDefault.value }}
globalDefault: false
description: "Priority class for Spyderbat Nano Agent pods"
{{- end }}
