{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spyderbat-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.role }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
{{- if .Values.namespaceSpyderbat.enabled }}
    namespace: spyderbat
{{- end }}
{{- if not .Values.namespaceSpyderbat.enabled }}
    namespace: default
{{- end }}

{{- end }}
