{{- if .Values.aws.secretsmanager.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spyderbat-credentials
  namespace: spyderbat
  labels:
    {{- include "nanoagent.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.aws.secretsmanager.secretarn }}
        jmesPath:
          - path: "\"spyderbat-registration-key\""
            objectAlias: spyderbat-registration-key
{{- end }}