apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spyderbat-credentials
  namespace: spyderbat
  labels:
    {{- include "nanoagent.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-2:429857113775:secret:beau/dev/eks-csi-roobat-M1mBZk"
        jmesPath: 
          - path: "\"spyderbat-registration-key\""
            objectAlias: spyderbat-registration-key

