{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "nanoagent.labels" . | nindent 4 }}
{{- if .Values.namespaceSpyderbat.enabled }}
  namespace: spyderbat
{{- end }}
{{- if not .Values.namespaceSpyderbat.enabled }}
  namespace: default
{{- end }}


{{- end }}
