{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "nanoagent.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::429857113775:role/eksctl-amazing-rainbow-1689885478-addon-iams-Role1-O1Z4QM13CADJ
  namespace: {{ .Release.Namespace }}


{{- end }}
