{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "nanoagent.labels" . | nindent 4 }}
  annotations:
{{- if eq .Values.aws.secretsmanager.enabled true }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.secretsmanager.rolearn }}
{{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
