apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spyderbat-cluster-write
rules:

- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["delete", "watch", "get", "list"]


